<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.master" AutoEventWireup="true" CodeFile="User.aspx.cs" Inherits="Admin_User" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="divAdmin">
         <div style="font-size: 24px; color: #007583; padding-left: 0px; font-weight: bold">Brúkarayvirlit <br />
         </div>
        <div>
            <br/>
<asp:GridView ID="gvDetails" runat="server" CssClass="GridView" AutoGenerateColumns="false" 
AutoGenerateDeleteButton="true" AutoGenerateEditButton="true"
onrowcancelingedit="gvDetails_RowCancelingEdit"
onrowdeleting="gvDetails_RowDeleting" onrowediting="gvDetails_RowEditing"
onrowupdating="gvDetails_RowUpdating" BorderColor="White" BorderStyle="None">

<Columns>
<asp:BoundField DataField="UserName" HeaderText="Brúkaranavn" ReadOnly="true"/>
<asp:BoundField DataField="Email" HeaderText="Teldupostur" />
    <asp:BoundField DataField="LastActivityDate" dataformatstring="{0:MM/dd/yy H:mm:ss}" HeaderText="Seinasta login" />
</Columns>
</asp:GridView>
<asp:Label ID="lblResult" runat="server" Font-Bold="true"/>
</div>
    <br/>
    </div>

</asp:Content>

